### ISSUE TITLE
the implementation details of NCE loss

### ISSUE THREAD

**Issue by LeoooooMM** [haha-lisa/Diffstyler#4]
Hello! Thank you for such an excellent project, could you please share the implementation details of Patch NCE loss? At present, I want to calculate the NCE loss of two images, and I hope to know the specific implementation details of this loss in the paper

**Comment by Jaredddddd** [comment]
> Hello! Thank you for such an excellent project, could you please share the implementation details of Patch NCE loss? At present, I want to calculate the NCE loss of two images, and I hope to know the specific implementation details of this loss in the paper

I also encountered this problem,have you solved it?

**Comment by haha-lisa** [comment]
more details please see https://github.com/taesungp/contrastive-unpaired-translation
