### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Dumeowmeow** [haha-lisa/Diffstyler#5]
Algorithm 2 doesn't correspond to the code, for example, w and 1-w are not represented, and what does this line in the code mean?
![QQ图片20240109194127](https://github.com/haha-lisa/Diffstyler/assets/99797884/fd1320c9-810c-49aa-9d2c-7fc95e5bc72c)

**Comment by haha-lisa** [comment]
Sorry for the different naming of the guidance parameters, but the essence is the same
