### ISSUE TITLE
 Thank you for such an excellent project

### ISSUE THREAD

**Issue by Songjiacun** [haha-lisa/Diffstyler#7]
Thank you for such an excellent project,I believe this is a significant contribution to computer vision. Could you provide some code related to clip score?

**Comment by haha-lisa** [comment]
I would recommend the following:
https://github.com/Taited/clip-score
https://github.com/openai/CLIP
https://github.com/XavierXiao/Dreamboo
th-Stable-Diffusion/blob/12fa9509f644ca1bb84c5869fe9f54ed1447cafc/evaluation/clip_eval.py
https://github.com/mehdidc/DALLE_clip_score
