### ISSUE TITLE
The image occured in the paper

### ISSUE THREAD

**Issue by leapxcheng** [haha-lisa/Diffstyler#9]
Can you provide the whole image for style transfer in the paper?

**Comment by haha-lisa** [comment]
> Can you provide the whole image for style transfer in the paper?

All content images are from pexels website, you can download your favourite images by yourself.

**Comment by zhentao-zou** [comment]
Your model is only used the pre-trained model, and does not paird image datasets to train?

**Comment by haha-lisa** [comment]
> Your model is only used the pre-trained model, and does not paird image datasets to train?

I misunderstood and thought you were referring to the content images that appear in the article. It's not pairs of images for training. The content image data used to train the model is at this link 👉 https://github.com/google-research-datasets/conceptual-12m. And the art image data used to train the model is at this link 👉 https://www.wikiart.org/.

**Comment by haha-lisa** [comment]
Email me (994082739@qq.com) if you need pictures
